version: "3.4"

services:
  rails_app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    image: rails_app
    container_name: rails_app
    ports:
      - "3000:3000"
    networks:
      - app_network
    env_file: rails_app.env

  webserver:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    image: webserver
    container_name: webserver
    ports:
      - "8080:80"
    networks:
      - app_network

  postgres:
    image: postgres:13.3
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: SecurePass#9876
      POSTGRES_DB: mydb
    networks:
      - app_network
                   
networks:
  app_network:
    driver: bridge
