name: Deploy Rails App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Terraform Init & Apply
      run: |
        cd infrastructure
        terraform init
        terraform apply -auto-approve

    - name: Login to ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 975050146518.dkr.ecr.us-east-1.amazonaws.com

    - name: Build and Push Docker image
      run: |
        docker build -t rails_app .
        docker tag rails_app:latest 975050146518.dkr.ecr.us-east-1.amazonaws.com/rails-app-repo:latest
        docker push 975050146518.dkr.ecr.us-east-1.amazonaws.com/rails-app-repo:latest

